AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Lambda function with Airtable and XLSX.js libraries in a layer.

Resources:
  ReonomyUploadApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  # Lambda Layer definition
  AirtableXLSXLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AirtableXLSXLayer
      Description: Layer containing Airtable and XLSX libraries
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs16.x
        - nodejs20.x
      LicenseInfo: 'MIT'

  # Lambda Function using the layer
  ReonomyUploadFunction:
    Type: AWS::Serverless::Function
    Properties: 
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./src/  # Points to the directory containing your Lambda function code
      Layers:
        - !Ref AirtableXLSXLayer  # Reference the layer created above
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ADDRESS_BASE_ID: !Sub "tblrIqZqCE8traVpK"
          API_KEY: !Sub "patEpKazaSEG3jtnx.c2562f5e3cc01897257fac0765872579de738b8e98aa216dd65209a3d31d0cfd"
          BASE_ID: !Sub "appO56WeZ7NuRAQn6"
          CONTACT_BASE_ID: !Sub "tbluIduGmCLHiKMN2"
          EMAIL_BASE_ID: !Sub "tblTlnJWr3hEPOQ2X"
          PHONE_BASE_ID: !Sub "tblJctmyWw4xni6nM"
          PROPERTY_BASE_ID: !Sub "tblLPGq49pjO9pZY1"
          PROPERTY_HOLDING_COMPANY_BASE_ID: !Sub "tblQyJUMmGscpOhEp"
          
      Events:
        ReonomyUploadPostApi:
          Type: Api
          Properties:
            Path: /
            RestApiId: !Ref ReonomyUploadApi
            Method: POST

Outputs:
  LambdaFunction:
    Description: "The Lambda function ARN"
    Value: !Ref ReonomyUploadFunction

  LambdaLayerVersionArn:
    Description: "Lambda Layer Version ARN"
    Value: !Ref AirtableXLSXLayer

  ReonomyUploadApi:
    Description: "Api gateway url for renome update"
    Value:
      Fn::Sub: "https://${ReonomyUploadApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"